### ISSUE TITLE
require 'sinatra/base' is not enough

### ISSUE THREAD

**Issue by fappelman** [codeplant/sinatra-simple-navigation#4]
The problem is that the code only works if I do a require 'sinatra' instead of require 'sinatra/base' which it should be. Taking the example of your documentation actually shows the problem:

**$ cat t.rb**
    require 'rubygems'
    require 'sinatra/base'
    require 'sinatra/simple-navigation'

```
class MyApp < Sinatra::Base
  register Sinatra::SimpleNavigation

  # Your app code goes here
end
```

**$ ruby t.rb**
    /Users/fred/.rvm/gems/ruby-1.9.3-p547@amanager/gems/simple-navigation-3.13.0/lib/simple_navigation.rb:89:in `join': can't convert nil into String (TypeError)
      from /Users/fred/.rvm/gems/ruby-1.9.3-p547@amanager/gems/simple-navigation-3.13.0/lib/simple_navigation.rb:89:in`default_config_file_path'
      from /Users/fred/.rvm/gems/ruby-1.9.3-p547@amanager/gems/simple-navigation-3.13.0/lib/simple_navigation.rb:58:in `set_env'
      from /Users/fred/.rvm/gems/ruby-1.9.3-p547@amanager/gems/simple-navigation-3.13.0/lib/simple_navigation/adapters/sinatra.rb:7:in`register'
      from /Users/fred/.rvm/gems/ruby-1.9.3-p547@amanager/gems/sinatra-simple-navigation-3.7.0/lib/sinatra/simple_navigation.rb:9:in `registered'
      from /Users/fred/.rvm/gems/ruby-1.9.3-p547@global/gems/sinatra-1.4.5/lib/sinatra/base.rb:1391:in`block in register'
      from /Users/fred/.rvm/gems/ruby-1.9.3-p547@global/gems/sinatra-1.4.5/lib/sinatra/base.rb:1389:in `each'
      from /Users/fred/.rvm/gems/ruby-1.9.3-p547@global/gems/sinatra-1.4.5/lib/sinatra/base.rb:1389:in`register'
      from t.rb:6:in `<class:MyApp>'
      from t.rb:5:in`<main>'
**$ ruby -v**
ruby 1.9.3p547 (2014-05-14 revision 45962) [x86_64-darwin13.3.0]
**$ gem list**

```
*** LOCAL GEMS ***

activesupport (4.1.4)
bigdecimal (1.1.0)
builder (3.2.2)
bundler (1.6.3)
bundler-unload (1.0.2)
executable-hooks (1.3.2)
faraday (0.9.0)
gem-wrappers (1.2.5)
geminabox (0.12.4)
haml (4.0.5)
httpclient (2.4.0)
i18n (0.6.11)
io-console (0.3)
json (1.8.1, 1.5.5)
minitest (5.4.0, 2.5.1)
multipart-post (2.0.0)
mysql (2.9.1)
nesty (1.0.2)
rack (1.5.2)
rack-protection (1.5.3)
rake (0.9.2.2)
rbgeneral (1.8)
rbosx (1.0)
rdoc (3.9.5)
remhost (1.0.10)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
sass (3.3.10)
shotgun (0.9)
simple-navigation (3.13.0)
sinatra (1.4.5)
sinatra-simple-navigation (3.7.0)
thread_safe (0.3.4)
tilt (2.0.1, 1.3.4)
tzinfo (1.2.1)
```

**Comment by stefan-kolb** [comment]
@andi I experience the same problem. If you replace require 'sinatra' by 'sinatra/base' inside the config.ru of your sample application it will break. Should be related to calling `Sinatra::Application` for retrieving the Sinatra root folder. Maybe you can recheck this.

**Comment by andi** [comment]
Ok, thx. I will take a look...

**Comment by andi** [comment]
I can't come up with a better solution for fetching root and environment other than Sinatra::Application.root and Sinatra::Application.environment. Anyone?

**Comment by stefan-kolb** [comment]
I'm not an expert on this, but I found some hints that could help. Most of my ideas are taken from: http://www.sinatrarb.com/extensions.html

At least I think the extension should definitely work without the need to require `sinatra`, but only `sinatra/base` as stated there:
> Never require 'sinatra' in your extension. You should only ever need to require 'sinatra/base'. The reason for this is that require 'sinatra' is what triggers the classic style – extensions should never trigger the classic style.

For the environment it can be just `Sinatra::Base.environment`. This should be set everytime.
The problem is to retrieve the `root` folder on modular apps, which is often just `nil`.
The following quote could help to retrieve this information:
> The Module.registered method is called immediately after the extension module is added to the Sinatra::Base subclass and is passed the class that the module was registered with.

So we can probably pass the `app` reference of the registered method to `::SimpleNavigation.register` and then just call `app.root`and `app.environment`

I hope I'm not on the wrong track here, but this is what I could find at first.

**Comment by andi** [comment]
> So we can probably pass the app reference of the registered method to ::SimpleNavigation.register and then just call app.root and app.environment

This was my initial idea, but app.root return nil for modular style app

**Comment by stefan-kolb** [comment]
I did a quick test by modifying the `sinatra-simple-navigation`Gem:
```ruby    
def self.registered(app)
      app.helpers ::SimpleNavigation::Helpers
      puts 'Root: ' << app.root.to_s
      puts 'ENV: ' << app.environment.to_s
      ::SimpleNavigation.register
    end
```
and used the `simple-navigation-demo` app and it returns:

```
Root: C:/Users/Administrator/Documents/GitHub/simple-navigation-demo/sinatra
ENV: development
```

**Comment by stefan-kolb** [comment]
I did a quick test by modifying the `sinatra-simple-navigation`Gem:
```ruby    
def self.registered(app)
      app.helpers ::SimpleNavigation::Helpers
      puts 'Root: ' << app.root.to_s
      puts 'ENV: ' << app.environment.to_s
      ::SimpleNavigation.register
    end
```
and used the `simple-navigation-demo` app and it returns:

```
Root: C:/Users/Administrator/Documents/GitHub/simple-navigation-demo/sinatra
ENV: development
```

**Comment by andi** [comment]
so what's the content of your config.ru?

**Comment by stefan-kolb** [comment]
```ruby
$: << File.dirname(__FILE__)

require 'rubygems'
require 'sinatra/base'
require 'sample_app'

run SimpleNavigationApp
```

**Comment by stefan-kolb** [comment]
Check out these forks, so you can see if I'm on the right track or not.

https://github.com/stefan-kolb/simple-navigation-demo
https://github.com/stefan-kolb/simple-navigation
https://github.com/stefan-kolb/sinatra-simple-navigation

**Comment by andi** [comment]
Hmm, I'm puzzled. That's exactly what I tried yesterday... I'll retry...

**Comment by andi** [comment]
For me app.root is always nil... Not sure why. Can you try to include the src version of the respective gems with :path in your Gemfiles, i.e.

- in Gemfile of demo project, refer to simple-navigation and sinatra-simple-navigation via :path
- in Gemfile of sinatra-simple-navigation, refer to simple-navigation via :path

Thanks!

**Comment by stefan-kolb** [comment]
I've commited the vendor/cache directory at https://github.com/stefan-kolb/simple-navigation-demo. You should be able to install the gems via `bundle install --local`
Hope this helps.

**Comment by andi** [comment]
Ok, when trying with your gems it works... Probably it's an issue when trying to access the root when you include a gem via the :path option in the gemfile? Anyway, guess we're good to go... Will release updated versions in the next couple of days...

**Comment by stefan-kolb** [comment]
I've created pull requests with the code changes I've done for the tests in each of the repositories.
Maybe it can save some time for you.
Feel free to adapt it or tell me if additional changes need to be done!

https://github.com/codeplant/simple-navigation/pull/175
https://github.com/codeplant/sinatra-simple-navigation/pull/5
https://github.com/codeplant/simple-navigation-demo/pull/3

**Comment by andi** [comment]
Ok, thanks. I guess this is not a show stopper, so we will release simple-navigation 4 anyway soon and we'll integrate it there.
